version: "3.9"

services:
  app:...
    container_name: donorcc_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:3000"
    command: sh -c "pnpm install && pnpm build && pnpm start"
