services:
version: '3.9'  # can remove `version` if Prisma complains
  app:
    build: .
    container_name: donorconnect_app
    ports:
      - "80:3000"
    env_file:
      - .env      # during local development
    environment:
      DATABASE_URL: ${DATABASE_URL}  # GitHub secret injects here
