version: "3.9"

services:
  app:
    build: .
    container_name: donorcc_app
    restart: unless-stopped
    ports:
      - "80:3000"
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "pnpm install && pnpm build && pnpm start"
